site_name: "NServer: Python DNS Name Server Framework"
site_url: https://nhairs.github.io/nserver
repo_url: https://github.com/nhairs/nserver
edit_uri: tree/master/docs
copyright: "Copyright &copy; Nicholas Hairs</a>"
watch:
  - mkdocs.yml
  - README.md
  - src/nserver

nav:
  - "Home": index.md
  - quickstart.md
  - middleware.md
  - error-handling.md
  - subserver-blueprint.md
  - production-deployment.md
  - changelog.md
  - external-resources.md
  - API Reference:
    - ... | reference/nserver/*

theme:
  name: material

  icon:
    logo: material/server-network

  features:
    - navigation.instant
    - navigation.sections
    - navigation.indexes
    - navigation.expand
    - navigation.top
    - content.code.annotate
    - content.code.copy
    - toc.follow

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nhairs/nserver
  version:
    provider: mike

markdown_extensions:
  - toc:
      permalink: "🔗"
  - admonition
  - def_list
  - mdx_truly_sane_lists
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.caret

plugins:
  - autorefs
  - search:
      lang: en
  - awesome-pages:
      collapse_single_pages: true
  - gen-files:
      scripts:
        - scripts/gen_ref_nav.py
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths:
            - src
          #import:
          #  - https://docs.python.org/3/objects.inv
          #  - https://mkdocstrings.github.io/objects.inv
          #  - https://mkdocstrings.github.io/griffe/objects.inv
          options:
            filters:
              - "!^_"
            heading_level: 1
            inherited_members: true
            merge_init_into_class: true
            #preload_modules: []
            separate_signature: true
            show_root_heading: true
            show_root_full_path: true
            show_signature_annotations: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            summary: true
            unwrap_annotated: true
            show_source: false
  - literate-nav:
      nav_file: SUMMARY.txt
  - mike:
      canonical_version: latest
